
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'protonovea-nodes'
    static_configs:
      - targets:
          - 'city-node-1.domain.com:9100'
          - 'city-node-2.domain.com:9100'
          - 'city-node-3.domain.com:9100'
